# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

target 'JKPhotoBrowser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JKPhotoBrowser

  # 1.1.0
  pod 'Masonry'
  # 5.9.4
  pod 'SDWebImage'
  pod 'SDWebImageWebPCoder'
  
  pod 'AppleDevices'
  
  pod 'LookinServer', :configurations => ['Debug']
  #pod 'JKImageBrowser', '~> 1.0.9'

end
